### ISSUE TITLE
Binding errors in output log

### ISSUE THREAD

**Issue by MaxMahem** [moviegear/LoadingIndicators.Avalonia#2]
This doesn't appear to break anything, but I am getting some binding errors in the output log, even when no binding for the property is in play. The specific error I am getting are a handful off:
```
[Binding]Error in binding to 'Avalonia.Animation.Animation'.'SpeedRatio': 'Null value in expression '{empty}' at '$parent[LoadingIndicator, 0]'.'(Animation #4085744)
```
With various different frame numbers, even though SpeedRatio is not bound. 

The xaml I am using is:
```xml
<li:LoadingIndicator Name="LoadingIndicator" 
  IsActive="{Binding ApiTestManager.TestRunning^}" 
  Mode="Wave" 
  SpeedRatio="1.0"
  MinWidth="0" 
  Width="{Binding #TestButton.Bounds.Width}"
  MinHeight="0" 
  Height="{Binding #TestButton.Bounds.Height}" 
  HorizontalAlignment="Stretch" />
```

love the control btw, thanks for it!

**Comment by moviegear** [comment]
As far as I know, this is an Avalonia problem: AvaloniaUI/Avalonia#5762. Should be fixed in version 11.1.
Sorry for late answer.
